[2024-01-30T19:30:01.326+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manage_data_lake_dag.dataproc_job_raw_to_formatted scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-01-30T19:30:01.333+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manage_data_lake_dag.dataproc_job_raw_to_formatted scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-01-30T19:30:01.333+0000] {taskinstance.py:2170} INFO - Starting attempt 6 of 6
[2024-01-30T19:30:01.349+0000] {taskinstance.py:2191} INFO - Executing <Task(DataprocSubmitJobOperator): dataproc_job_raw_to_formatted> on 2024-01-17 00:00:00+00:00
[2024-01-30T19:30:01.355+0000] {standard_task_runner.py:60} INFO - Started process 77162 to run task
[2024-01-30T19:30:01.362+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'manage_data_lake_dag', 'dataproc_job_raw_to_formatted', 'scheduled__2024-01-17T00:00:00+00:00', '--job-id', '402', '--raw', '--subdir', 'DAGS_FOLDER/data_lake_dag.py', '--cfg-path', '/tmp/tmpr_ns27gs']
[2024-01-30T19:30:01.365+0000] {standard_task_runner.py:88} INFO - Job 402: Subtask dataproc_job_raw_to_formatted
[2024-01-30T19:30:01.414+0000] {task_command.py:423} INFO - Running <TaskInstance: manage_data_lake_dag.dataproc_job_raw_to_formatted scheduled__2024-01-17T00:00:00+00:00 [running]> on host instance-1.europe-west9-a.c.data-lake-project-409321.internal
[2024-01-30T19:30:01.484+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juniortemgoua0' AIRFLOW_CTX_DAG_ID='manage_data_lake_dag' AIRFLOW_CTX_TASK_ID='dataproc_job_raw_to_formatted' AIRFLOW_CTX_EXECUTION_DATE='2024-01-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-17T00:00:00+00:00'
[2024-01-30T19:30:01.487+0000] {dataproc.py:2317} INFO - Submitting job
[2024-01-30T19:30:01.491+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-30T19:30:01.496+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-30T19:30:01.647+0000] {dataproc.py:2329} INFO - Job f4f46b47-cd82-46c3-9439-aed4f4bd1938 submitted successfully.
[2024-01-30T19:30:01.659+0000] {dataproc.py:2363} INFO - Waiting for job f4f46b47-cd82-46c3-9439-aed4f4bd1938 to complete
[2024-01-30T19:30:41.958+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 2364, in execute
    self.hook.wait_for_job(
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 482, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/dataproc.py", line 740, in wait_for_job
    raise AirflowException(f"Job failed:\n{job}")
airflow.exceptions.AirflowException: Job failed:
reference {
  project_id: "data-lake-project-409321"
  job_id: "f4f46b47-cd82-46c3-9439-aed4f4bd1938"
}
placement {
  cluster_name: "cluster-f499"
  cluster_uuid: "13fc8c1e-24fd-4462-8a44-4c3a49636ea2"
}
spark_job {
  main_class: "RawToFormatted"
  args: "gs://data-lake-buck"
  args: "dataproc"
  jar_file_uris: "gs://data-lake-buck/spark_job_2.12-0.1.0.jar"
  properties {
    key: "spark.airflow.execution_date"
    value: "2024-01-17"
  }
}
status {
  state: ERROR
  details: "Job failed with message [Exception in thread \"main\" org.apache.spark.sql.AnalysisException: Path does not exist: gs://data-lake-buck/raw/football_data/competitions/2024-01-17/*.json]. Additional details can be found at:\nhttps://console.cloud.google.com/dataproc/jobs/f4f46b47-cd82-46c3-9439-aed4f4bd1938?project=data-lake-project-409321&region=europe-west9\ngcloud dataproc jobs wait \'f4f46b47-cd82-46c3-9439-aed4f4bd1938\' --region \'europe-west9\' --project \'data-lake-project-409321\'\nhttps://console.cloud.google.com/storage/browser/dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/f4f46b47-cd82-46c3-9439-aed4f4bd1938/\ngs://dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/f4f46b47-cd82-46c3-9439-aed4f4bd1938/driveroutput.*"
  state_start_time {
    seconds: 1706643037
    nanos: 539498000
  }
}
status_history {
  state: PENDING
  state_start_time {
    seconds: 1706643001
    nanos: 631405000
  }
}
status_history {
  state: SETUP_DONE
  state_start_time {
    seconds: 1706643001
    nanos: 678652000
  }
}
status_history {
  state: RUNNING
  state_start_time {
    seconds: 1706643001
    nanos: 910912000
  }
}
yarn_applications {
  name: "RawToFormatted"
  state: FINISHED
  progress: 1
  tracking_url: "http://cluster-f499-m.europe-west9-c.c.data-lake-project-409321.internal.:8088/proxy/application_1706622505355_0142/"
}
driver_output_resource_uri: "gs://dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/f4f46b47-cd82-46c3-9439-aed4f4bd1938/driveroutput"
driver_control_files_uri: "gs://dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/f4f46b47-cd82-46c3-9439-aed4f4bd1938/"
job_uuid: "f4f46b47-cd82-46c3-9439-aed4f4bd1938"
done: true

[2024-01-30T19:30:41.962+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=manage_data_lake_dag, task_id=dataproc_job_raw_to_formatted, execution_date=20240117T000000, start_date=20240130T193001, end_date=20240130T193041
[2024-01-30T19:30:41.974+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 402 for task dataproc_job_raw_to_formatted (Job failed:
reference {
  project_id: "data-lake-project-409321"
  job_id: "f4f46b47-cd82-46c3-9439-aed4f4bd1938"
}
placement {
  cluster_name: "cluster-f499"
  cluster_uuid: "13fc8c1e-24fd-4462-8a44-4c3a49636ea2"
}
spark_job {
  main_class: "RawToFormatted"
  args: "gs://data-lake-buck"
  args: "dataproc"
  jar_file_uris: "gs://data-lake-buck/spark_job_2.12-0.1.0.jar"
  properties {
    key: "spark.airflow.execution_date"
    value: "2024-01-17"
  }
}
status {
  state: ERROR
  details: "Job failed with message [Exception in thread \"main\" org.apache.spark.sql.AnalysisException: Path does not exist: gs://data-lake-buck/raw/football_data/competitions/2024-01-17/*.json]. Additional details can be found at:\nhttps://console.cloud.google.com/dataproc/jobs/f4f46b47-cd82-46c3-9439-aed4f4bd1938?project=data-lake-project-409321&region=europe-west9\ngcloud dataproc jobs wait \'f4f46b47-cd82-46c3-9439-aed4f4bd1938\' --region \'europe-west9\' --project \'data-lake-project-409321\'\nhttps://console.cloud.google.com/storage/browser/dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/f4f46b47-cd82-46c3-9439-aed4f4bd1938/\ngs://dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/f4f46b47-cd82-46c3-9439-aed4f4bd1938/driveroutput.*"
  state_start_time {
    seconds: 1706643037
    nanos: 539498000
  }
}
status_history {
  state: PENDING
  state_start_time {
    seconds: 1706643001
    nanos: 631405000
  }
}
status_history {
  state: SETUP_DONE
  state_start_time {
    seconds: 1706643001
    nanos: 678652000
  }
}
status_history {
  state: RUNNING
  state_start_time {
    seconds: 1706643001
    nanos: 910912000
  }
}
yarn_applications {
  name: "RawToFormatted"
  state: FINISHED
  progress: 1
  tracking_url: "http://cluster-f499-m.europe-west9-c.c.data-lake-project-409321.internal.:8088/proxy/application_1706622505355_0142/"
}
driver_output_resource_uri: "gs://dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/f4f46b47-cd82-46c3-9439-aed4f4bd1938/driveroutput"
driver_control_files_uri: "gs://dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/f4f46b47-cd82-46c3-9439-aed4f4bd1938/"
job_uuid: "f4f46b47-cd82-46c3-9439-aed4f4bd1938"
done: true
; 77162)
[2024-01-30T19:30:41.992+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-30T19:30:42.011+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
