[2024-01-30T03:13:48.215+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manage_data_lake_dag.extract_data_and_load_to_gs scheduled__2024-01-08T00:00:00+00:00 [queued]>
[2024-01-30T03:13:48.220+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manage_data_lake_dag.extract_data_and_load_to_gs scheduled__2024-01-08T00:00:00+00:00 [queued]>
[2024-01-30T03:13:48.221+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 6
[2024-01-30T03:13:48.233+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_data_and_load_to_gs> on 2024-01-08 00:00:00+00:00
[2024-01-30T03:13:48.238+0000] {standard_task_runner.py:60} INFO - Started process 25136 to run task
[2024-01-30T03:13:48.244+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'manage_data_lake_dag', 'extract_data_and_load_to_gs', 'scheduled__2024-01-08T00:00:00+00:00', '--job-id', '156', '--raw', '--subdir', 'DAGS_FOLDER/data_lake_dag.py', '--cfg-path', '/tmp/tmpqbbfte2s']
[2024-01-30T03:13:48.246+0000] {standard_task_runner.py:88} INFO - Job 156: Subtask extract_data_and_load_to_gs
[2024-01-30T03:13:48.292+0000] {task_command.py:423} INFO - Running <TaskInstance: manage_data_lake_dag.extract_data_and_load_to_gs scheduled__2024-01-08T00:00:00+00:00 [running]> on host instance-1.europe-west9-a.c.data-lake-project-409321.internal
[2024-01-30T03:13:48.347+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juniortemgoua0' AIRFLOW_CTX_DAG_ID='manage_data_lake_dag' AIRFLOW_CTX_TASK_ID='extract_data_and_load_to_gs' AIRFLOW_CTX_EXECUTION_DATE='2024-01-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-08T00:00:00+00:00'
[2024-01-30T03:13:48.546+0000] {logging_mixin.py:188} INFO - Login to bucket data-lake-buck
[2024-01-30T03:13:48.630+0000] {logging_mixin.py:188} INFO - Request failed with code: 429
[2024-01-30T03:13:48.718+0000] {logging_mixin.py:188} INFO - Request failed with code: 429
[2024-01-30T03:13:48.719+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-30T03:13:48.727+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=manage_data_lake_dag, task_id=extract_data_and_load_to_gs, execution_date=20240108T000000, start_date=20240130T031348, end_date=20240130T031348
[2024-01-30T03:13:48.776+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-30T03:13:48.798+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
