[2024-01-30T03:13:29.599+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manage_data_lake_dag.extract_data_and_load_to_gs scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2024-01-30T03:13:29.604+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manage_data_lake_dag.extract_data_and_load_to_gs scheduled__2024-01-04T00:00:00+00:00 [queued]>
[2024-01-30T03:13:29.605+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 6
[2024-01-30T03:13:29.618+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): extract_data_and_load_to_gs> on 2024-01-04 00:00:00+00:00
[2024-01-30T03:13:29.623+0000] {standard_task_runner.py:60} INFO - Started process 25076 to run task
[2024-01-30T03:13:29.629+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'manage_data_lake_dag', 'extract_data_and_load_to_gs', 'scheduled__2024-01-04T00:00:00+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/data_lake_dag.py', '--cfg-path', '/tmp/tmp7nfy_186']
[2024-01-30T03:13:29.632+0000] {standard_task_runner.py:88} INFO - Job 152: Subtask extract_data_and_load_to_gs
[2024-01-30T03:13:29.677+0000] {task_command.py:423} INFO - Running <TaskInstance: manage_data_lake_dag.extract_data_and_load_to_gs scheduled__2024-01-04T00:00:00+00:00 [running]> on host instance-1.europe-west9-a.c.data-lake-project-409321.internal
[2024-01-30T03:13:29.758+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juniortemgoua0' AIRFLOW_CTX_DAG_ID='manage_data_lake_dag' AIRFLOW_CTX_TASK_ID='extract_data_and_load_to_gs' AIRFLOW_CTX_EXECUTION_DATE='2024-01-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-04T00:00:00+00:00'
[2024-01-30T03:13:29.962+0000] {logging_mixin.py:188} INFO - Login to bucket data-lake-buck
[2024-01-30T03:13:30.052+0000] {logging_mixin.py:188} INFO - Request failed with code: 429
[2024-01-30T03:13:30.146+0000] {logging_mixin.py:188} INFO - Request failed with code: 429
[2024-01-30T03:13:30.147+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-30T03:13:30.156+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=manage_data_lake_dag, task_id=extract_data_and_load_to_gs, execution_date=20240104T000000, start_date=20240130T031329, end_date=20240130T031330
[2024-01-30T03:13:30.201+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-30T03:13:30.222+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
