[2024-01-30T17:59:21.761+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manage_data_lake_dag.dataproc_job_raw_to_formatted scheduled__2024-01-07T00:00:00+00:00 [queued]>
[2024-01-30T17:59:21.768+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manage_data_lake_dag.dataproc_job_raw_to_formatted scheduled__2024-01-07T00:00:00+00:00 [queued]>
[2024-01-30T17:59:21.768+0000] {taskinstance.py:2170} INFO - Starting attempt 6 of 6
[2024-01-30T17:59:21.783+0000] {taskinstance.py:2191} INFO - Executing <Task(DataprocSubmitJobOperator): dataproc_job_raw_to_formatted> on 2024-01-07 00:00:00+00:00
[2024-01-30T17:59:21.789+0000] {standard_task_runner.py:60} INFO - Started process 71407 to run task
[2024-01-30T17:59:21.795+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'manage_data_lake_dag', 'dataproc_job_raw_to_formatted', 'scheduled__2024-01-07T00:00:00+00:00', '--job-id', '338', '--raw', '--subdir', 'DAGS_FOLDER/data_lake_dag.py', '--cfg-path', '/tmp/tmprpxtmcqi']
[2024-01-30T17:59:21.798+0000] {standard_task_runner.py:88} INFO - Job 338: Subtask dataproc_job_raw_to_formatted
[2024-01-30T17:59:21.849+0000] {task_command.py:423} INFO - Running <TaskInstance: manage_data_lake_dag.dataproc_job_raw_to_formatted scheduled__2024-01-07T00:00:00+00:00 [running]> on host instance-1.europe-west9-a.c.data-lake-project-409321.internal
[2024-01-30T17:59:21.917+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juniortemgoua0' AIRFLOW_CTX_DAG_ID='manage_data_lake_dag' AIRFLOW_CTX_TASK_ID='dataproc_job_raw_to_formatted' AIRFLOW_CTX_EXECUTION_DATE='2024-01-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-07T00:00:00+00:00'
[2024-01-30T17:59:21.919+0000] {dataproc.py:2317} INFO - Submitting job
[2024-01-30T17:59:21.924+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-30T17:59:21.929+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-30T17:59:22.108+0000] {dataproc.py:2329} INFO - Job 44d787f0-d9b0-4636-9c8e-b79f30b85123 submitted successfully.
[2024-01-30T17:59:22.119+0000] {dataproc.py:2363} INFO - Waiting for job 44d787f0-d9b0-4636-9c8e-b79f30b85123 to complete
[2024-01-30T18:00:02.426+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/dataproc.py", line 2364, in execute
    self.hook.wait_for_job(
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 482, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/juniortemgoua0/DataLake/venv/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/dataproc.py", line 740, in wait_for_job
    raise AirflowException(f"Job failed:\n{job}")
airflow.exceptions.AirflowException: Job failed:
reference {
  project_id: "data-lake-project-409321"
  job_id: "44d787f0-d9b0-4636-9c8e-b79f30b85123"
}
placement {
  cluster_name: "cluster-f499"
  cluster_uuid: "13fc8c1e-24fd-4462-8a44-4c3a49636ea2"
}
spark_job {
  main_class: "RawToFormatted"
  args: "gs://data-lake-buck"
  args: "dataproc"
  jar_file_uris: "gs://data-lake-buck/spark_job_2.12-0.1.0.jar"
  properties {
    key: "spark.airflow.execution_date"
    value: "2024-01-07"
  }
}
status {
  state: ERROR
  details: "Job failed with message [Exception in thread \"main\" org.apache.spark.sql.AnalysisException: Path does not exist: gs://data-lake-buck/raw/football_data/competitions/2024-01-07/*.json]. Additional details can be found at:\nhttps://console.cloud.google.com/dataproc/jobs/44d787f0-d9b0-4636-9c8e-b79f30b85123?project=data-lake-project-409321&region=europe-west9\ngcloud dataproc jobs wait \'44d787f0-d9b0-4636-9c8e-b79f30b85123\' --region \'europe-west9\' --project \'data-lake-project-409321\'\nhttps://console.cloud.google.com/storage/browser/dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/44d787f0-d9b0-4636-9c8e-b79f30b85123/\ngs://dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/44d787f0-d9b0-4636-9c8e-b79f30b85123/driveroutput.*"
  state_start_time {
    seconds: 1706637596
    nanos: 365469000
  }
}
status_history {
  state: PENDING
  state_start_time {
    seconds: 1706637562
    nanos: 90417000
  }
}
status_history {
  state: SETUP_DONE
  state_start_time {
    seconds: 1706637562
    nanos: 137360000
  }
}
status_history {
  state: RUNNING
  state_start_time {
    seconds: 1706637562
    nanos: 369054000
  }
}
yarn_applications {
  name: "RawToFormatted"
  state: FINISHED
  progress: 1
  tracking_url: "http://cluster-f499-m.europe-west9-c.c.data-lake-project-409321.internal.:8088/proxy/application_1706622505355_0087/"
}
driver_output_resource_uri: "gs://dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/44d787f0-d9b0-4636-9c8e-b79f30b85123/driveroutput"
driver_control_files_uri: "gs://dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/44d787f0-d9b0-4636-9c8e-b79f30b85123/"
job_uuid: "44d787f0-d9b0-4636-9c8e-b79f30b85123"
done: true

[2024-01-30T18:00:02.430+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=manage_data_lake_dag, task_id=dataproc_job_raw_to_formatted, execution_date=20240107T000000, start_date=20240130T175921, end_date=20240130T180002
[2024-01-30T18:00:02.444+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 338 for task dataproc_job_raw_to_formatted (Job failed:
reference {
  project_id: "data-lake-project-409321"
  job_id: "44d787f0-d9b0-4636-9c8e-b79f30b85123"
}
placement {
  cluster_name: "cluster-f499"
  cluster_uuid: "13fc8c1e-24fd-4462-8a44-4c3a49636ea2"
}
spark_job {
  main_class: "RawToFormatted"
  args: "gs://data-lake-buck"
  args: "dataproc"
  jar_file_uris: "gs://data-lake-buck/spark_job_2.12-0.1.0.jar"
  properties {
    key: "spark.airflow.execution_date"
    value: "2024-01-07"
  }
}
status {
  state: ERROR
  details: "Job failed with message [Exception in thread \"main\" org.apache.spark.sql.AnalysisException: Path does not exist: gs://data-lake-buck/raw/football_data/competitions/2024-01-07/*.json]. Additional details can be found at:\nhttps://console.cloud.google.com/dataproc/jobs/44d787f0-d9b0-4636-9c8e-b79f30b85123?project=data-lake-project-409321&region=europe-west9\ngcloud dataproc jobs wait \'44d787f0-d9b0-4636-9c8e-b79f30b85123\' --region \'europe-west9\' --project \'data-lake-project-409321\'\nhttps://console.cloud.google.com/storage/browser/dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/44d787f0-d9b0-4636-9c8e-b79f30b85123/\ngs://dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/44d787f0-d9b0-4636-9c8e-b79f30b85123/driveroutput.*"
  state_start_time {
    seconds: 1706637596
    nanos: 365469000
  }
}
status_history {
  state: PENDING
  state_start_time {
    seconds: 1706637562
    nanos: 90417000
  }
}
status_history {
  state: SETUP_DONE
  state_start_time {
    seconds: 1706637562
    nanos: 137360000
  }
}
status_history {
  state: RUNNING
  state_start_time {
    seconds: 1706637562
    nanos: 369054000
  }
}
yarn_applications {
  name: "RawToFormatted"
  state: FINISHED
  progress: 1
  tracking_url: "http://cluster-f499-m.europe-west9-c.c.data-lake-project-409321.internal.:8088/proxy/application_1706622505355_0087/"
}
driver_output_resource_uri: "gs://dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/44d787f0-d9b0-4636-9c8e-b79f30b85123/driveroutput"
driver_control_files_uri: "gs://dataproc-staging-europe-west9-58760042001-uborul6i/google-cloud-dataproc-metainfo/13fc8c1e-24fd-4462-8a44-4c3a49636ea2/jobs/44d787f0-d9b0-4636-9c8e-b79f30b85123/"
job_uuid: "44d787f0-d9b0-4636-9c8e-b79f30b85123"
done: true
; 71407)
[2024-01-30T18:00:02.460+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-30T18:00:02.478+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
