[2024-01-30T20:07:37.730+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manage_data_lake_dag.dataproc_job_formatted_to_usage scheduled__2024-01-29T00:00:00+00:00 [queued]>
[2024-01-30T20:07:37.738+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manage_data_lake_dag.dataproc_job_formatted_to_usage scheduled__2024-01-29T00:00:00+00:00 [queued]>
[2024-01-30T20:07:37.738+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-01-30T20:07:37.754+0000] {taskinstance.py:2191} INFO - Executing <Task(DataprocSubmitJobOperator): dataproc_job_formatted_to_usage> on 2024-01-29 00:00:00+00:00
[2024-01-30T20:07:37.760+0000] {standard_task_runner.py:60} INFO - Started process 79601 to run task
[2024-01-30T20:07:37.766+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'manage_data_lake_dag', 'dataproc_job_formatted_to_usage', 'scheduled__2024-01-29T00:00:00+00:00', '--job-id', '431', '--raw', '--subdir', 'DAGS_FOLDER/data_lake_dag.py', '--cfg-path', '/tmp/tmpulvba2ml']
[2024-01-30T20:07:37.769+0000] {standard_task_runner.py:88} INFO - Job 431: Subtask dataproc_job_formatted_to_usage
[2024-01-30T20:07:37.814+0000] {task_command.py:423} INFO - Running <TaskInstance: manage_data_lake_dag.dataproc_job_formatted_to_usage scheduled__2024-01-29T00:00:00+00:00 [running]> on host instance-1.europe-west9-a.c.data-lake-project-409321.internal
[2024-01-30T20:07:37.887+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='juniortemgoua0' AIRFLOW_CTX_DAG_ID='manage_data_lake_dag' AIRFLOW_CTX_TASK_ID='dataproc_job_formatted_to_usage' AIRFLOW_CTX_EXECUTION_DATE='2024-01-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-29T00:00:00+00:00'
[2024-01-30T20:07:37.890+0000] {dataproc.py:2317} INFO - Submitting job
[2024-01-30T20:07:37.894+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-01-30T20:07:37.899+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-01-30T20:07:38.083+0000] {dataproc.py:2329} INFO - Job 46ad71d5-1453-4d3a-b225-736639156f8e submitted successfully.
[2024-01-30T20:07:38.095+0000] {dataproc.py:2363} INFO - Waiting for job 46ad71d5-1453-4d3a-b225-736639156f8e to complete
[2024-01-30T20:09:18.825+0000] {dataproc.py:2367} INFO - Job 46ad71d5-1453-4d3a-b225-736639156f8e completed successfully.
[2024-01-30T20:09:18.841+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=manage_data_lake_dag, task_id=dataproc_job_formatted_to_usage, execution_date=20240129T000000, start_date=20240130T200737, end_date=20240130T200918
[2024-01-30T20:09:18.900+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-30T20:09:18.912+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
